#!/usr/bin/env php
<?php
declare(strict_types = 1);

$paths = [
    'vendor/autoload.php',
    '../autoload.php',
    __DIR__ . '/../autoload.php',
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/../../vendor/autoload.php',
    getcwd() . '/vendor/autoload.php',
    getcwd() . '/../vendor/autoload.php',
];

foreach ($paths as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

use function Innmind\Genome\bootstrap;
use Innmind\CLI\{
    Main,
    Environment,
};
use Innmind\Url\Path;
use Innmind\OperatingSystem\OperatingSystem;

new class extends Main {
    protected function main(Environment $env, OperatingSystem $os): void
    {
        $run = bootstrap(
            new Path($env->variables()['GENOME'] ?? 'innmind'),
            $os->filesystem()->mount(
                new Path($env->variables()->get('HOME').'/.innmind/genome')
            ),
            $os->control(),
            $os->remote()->http()
        );
        $run($env);
    }
};
