#!/usr/bin/env php
<?php
declare(strict_types = 1);

$paths = [
    __DIR__.'/vendor/autoload.php',
    __DIR__ . '/../../../vendor/autoload.php',
];

foreach ($paths as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

use Innmind\Genome\Command;
use Innmind\CLI\Framework\{
    Main,
    Application,
};

new class extends Main {
    protected function configure(Application $app): Application
    {
        return $app
            ->useResilientOperatingSystem()
            ->commands(static fn($env, $os): array => [
                new Command\Express($os),
                new Command\Display($os),
            ]);
    }
};
